Fix location permission
Aychihuahuausa/walker-go pull request #22
Opened 2021-11-14 14:34 UTC by Aychihuahuausa

2021-11-14 17:57 UTC, heshambadawy requested changes

2021-11-14 17:57 UTC, heshambadawy commented on src/app/main-client/main-client.component.ts
> +        debugger
Remove debugger 

Add some user prompt like " plz go to setting and give the app the permission  "

2021-11-14 17:57 UTC, heshambadawy commented on src/app/main-client/main-client.component.ts
> +    if (granted) {
Does that check only or check and ask for permission too like that 
![image](https://user-images.githubusercontent.com/13408250/141692548-2444a102-2da8-4a76-a886-f6767efb72b3.png)

2021-11-14 17:57 UTC, heshambadawy commented on package.json
> +    "@ionic-native/android-permissions": "^5.36.0",
Can  address ios with u just add the base for Ios with u 
as when we start onIOS  we have something in place

2021-11-16 08:16 UTC, Aychihuahuausa commented on src/app/main-client/main-client.component.ts
> +    if (granted) {
give and ask permission

2021-11-16 08:17 UTC, Aychihuahuausa commented on package.json
> +    "@ionic-native/android-permissions": "^5.36.0",
I am not sure if this plugin work with IOS or not we have to build an see

2021-11-16 14:29 UTC, merged