Distance walker client
Aychihuahuausa/walker-go pull request #35
Opened 2021-12-29 22:06 UTC by Aychihuahuausa

Add storage to save distance that walker spend

2021-12-30 12:46 UTC, heshambadawy requested changes

2021-12-30 12:46 UTC, heshambadawy commented on src/app/main-client/main-client.component.ts
> +      if (!this.userService.currentWalker) {
Supposed not to reached here , if he isn't  already authorized

2021-12-30 12:46 UTC, heshambadawy commented on src/app/main-client/main-client.component.ts
> +          if (x.statusId !== RequestStatus.Cancel && x.statusId !== RequestStatus.Finished) {
Don't use the A b c names

2021-12-30 12:46 UTC, heshambadawy commented on src/app/main-client/walk-started/walk-started.component.ts
>    constructor(private cordovaService: CordovaService, public mainClientService: MainClientService,
Add space before any method "cc"

2021-12-30 12:46 UTC, heshambadawy commented on src/app/share/map/map.service.ts
> +    let location1 = { ...loc1 };
it's already object why u need spread it

2021-12-30 12:46 UTC, heshambadawy commented on src/app/share/map/map.service.ts
> -  distanceInKmBetweenEarthCoordinates = function (location1: Position, location2: Position) {
Is your testing assure that getting distance come in approximately accurate matter?
Need unit testing for that to let me handle it later and all similar "Todo Add "

2021-12-30 14:52 UTC, heshambadawy requested changes

2021-12-30 14:52 UTC, heshambadawy commented on src/app/main-client/main-client.component.ts
> +      if (!this.userService.currentWalker) {
ToDo later

2021-12-30 14:52 UTC, heshambadawy commented on src/app/main-client/main-client.component.ts
> +      if (!this.userService.currentWalker) {
Done, later consideration

2021-12-30 14:52 UTC, heshambadawy commented on src/app/main-client/main-client.component.ts
> +          if (x.statusId !== RequestStatus.Cancel && x.statusId !== RequestStatus.Finished) {
renaming

2021-12-30 14:52 UTC, heshambadawy commented on src/app/share/map/map.service.ts
> +    let location1 = { ...loc1 };
It's Done

2021-12-30 14:52 UTC, heshambadawy commented on src/app/main-client/main-client.component.ts
>    async getCurrentPostion() {
add watch position after getCurrentPoistion , and remove redenecy of code lines

2021-12-30 15:16 UTC, Aychihuahuausa commented on src/app/main-client/main-client.component.ts
>                this.mapService.clearMap();
done

2021-12-30 15:16 UTC, Aychihuahuausa commented on src/app/main-client/main-client.component.ts
>    async getCurrentPostion() {
done

2021-12-30 15:16 UTC, Aychihuahuausa commented on src/app/main-client/main-client.component.ts
> +          if (x.statusId !== RequestStatus.Cancel && x.statusId !== RequestStatus.Finished) {
done

2021-12-30 15:18 UTC, Aychihuahuausa commented on src/app/main-client/walk-started/walk-started.component.ts
>    constructor(private cordovaService: CordovaService, public mainClientService: MainClientService,
done

2021-12-31 15:42 UTC, heshambadawy approved these changes

2021-12-31 15:42 UTC, merged